.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. auroracoin_qt test_auroracoin_qt
clean: FORCE
	$(MAKE) -C .. auroracoin_qt_clean test_auroracoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_auroracoin_qt_check
auroracoin-qt auroracoin-qt.exe: FORCE
	 $(MAKE) -C .. auroracoin_qt
